#!/bin/zsh -f

mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
mpv ~/Videos/sleep/s/sword.mp4
